### ISSUE TITLE
Issue pushing to new branch. 

### ISSUE THREAD

**Issue by sammohammeduk** [GlamTam2000/NekoCafe#1]
Hello, I've cloned this repo and made some changes to a local branch, but when I try to push I get a 403..

`$ git push --set-upstream origin sam-001
remote: Permission to GlamTam2000/NekoCafe.git denied to sammohammeduk.
fatal: unable to access 'https://github.com/GlamTam2000/NekoCafe.git/': The requested URL returned error: 403`

I've never done this before on github, do you need to add me as a contributor or something?

**Comment by GlamTam2000** [comment]
I've never added anyone before lol, I'll do it in the morning 😅. I might separate each file to own branch as well . Thanks Sam

**Comment by GlamTam2000** [comment]
@sammohammeduk I've added you as a collaborator to repo, except invite. Thanks for the Colab 😊
